packages:
  - apps/*
  - packages/*
catalog:
  "@base-ui/react": ^1.0.0
  "@libsql/client": 0.15.15
  "@t3-oss/env-core": ^0.13.1
  "@t3-oss/env-nextjs": ^0.13.1
  "@tailwindcss/postcss": ^4.1.10
  "@types/node": ^22.13.14
  "@types/react": ^19.2.7
  "@types/react-dom": ^19.2.3
  babel-plugin-react-compiler: ^1.0.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  dotenv: ^17.2.2
  drizzle-kit: ^0.31.8
  drizzle-orm: ^0.45.1
  libsql: 0.5.22
  lint-staged: ^16.2.7
  lucide-react: ^0.546.0
  next: ^16.1.1
  next-themes: ^0.4.6
  oxfmt: ^0.26.0
  oxlint: ^1.49.0
  react: ^19.2.3
  react-dom: ^19.2.3
  shadcn: ^3.6.2
  simple-git-hooks: ^2.13.1
  sonner: ^2.0.5
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.10
  tw-animate-css: ^1.3.4
  "@typescript/native-preview": 7.0.0-dev.20260220.1
  typescript: ^5
  zod: ^4.1.13

onlyBuiltDependencies:
  - simple-git-hooks
